wandb_image_logger:
  _target_: src.utils.wandb_image_logger_callback.WandBImageLogger
  log_on_train: false
  log_on_val_test_pred: true
  val_test_pred_log_every_n_epochs: 1 
  val_test_pred_n_batches_to_visualize: -1
  val_test_pred_random_batches: false
  image_log_fn_name: "log_visualizations" # Must match the method in the LitModel
