wandb_image_logger:
  _target_: src.utils.wandb_image_logger_callback.WandBImageLogger
  log_every_n_epochs: 1 
  n_batches_to_visualize: 10
  random_batches: false
  image_log_fn_name: "log_visualizations" # Must match the method in the LitModel
  log_on_train_epoch: false
  log_on_val_epoch: true
